### ISSUE TITLE
Doctrine 2.6.1 compatibility

### ISSUE THREAD

**Issue by cyrilprevot** [APY/APYDataGridBundle#1001]
I got "Error: Expected Doctrine\ORM\Query\Lexer::T_FROM, got ':'" since 2.6.1 doctrine update.
The issue seem to be due to new DQL parsing. 
":" can't be use anymore in select clause and the bundle add "::" between subentity and field. Futhermore, function in Grid\Source annotation doesn't work anymore (field:count) cause of ":"

**Comment by DonCallisto** [comment]
Duplicate of #772

**Comment by DonCallisto** [comment]
@cyrilprevot take a look to the issue marked as duplicate and try what I've said there to check if the problem is gone.

I would appreciate a feedback from you.
Thanks.

**Comment by DonCallisto** [comment]
I've drafted a new release for this https://github.com/APY/APYDataGridBundle/releases/tag/3.1.2

**Comment by pavelmitko** [comment]
Hello @DonCallisto ,
The issue is not fixed. You have forgot about DQL functions!

`@GRID\Column(field="id:count")`
will be replaced as `SELECT count(_tableAlias.id) AS id:count` what will raise an error:
Doctrine\ORM\Query\QueryException : [Syntax Error] line 0, col 1142: Error: Expected Doctrine\ORM\Query\Lexer::T_IDENTIFIER, got 'id:count'

Grid/Source/Entity.php:222 -> $alias = $this->fromColIdToAlias($name); // helped. please investigate

**Comment by DonCallisto** [comment]
I'll take a look at this ASAP.
Thanks.

**Comment by DonCallisto** [comment]
@pavelmitko could you require this branch in `composer.json` and check if the issue go away?
https://github.com/APY/APYDataGridBundle/tree/Fix_DQL_Annotation

If so, I will merge it in master and release another bugfix version.

Let me know, thank you.

**Comment by ruprai** [comment]
Hi @DonCallisto.  I have tried the branch.  The correction appears to have fixed the issue.

**Comment by DonCallisto** [comment]
@ruprai thanks for the feedback.
