### ISSUE TITLE
Column with id "__action" doesn't exists after MassAction with getFilter method

### ISSUE THREAD

**Issue by plfort** [APY/APYDataGridBundle#709]
I use the getFilter($columnId) in a manipulateQuery callback: it works great.
But when the grid redirect after a MassAction I get this exception :

Column with id "__action" doesn't exists
500 Internal Server Error - InvalidArgumentException

Thrown by getColumnById

In fact, in the getFilters method some keys are deleted from sessionData :
```php
            $requestQueries = array(
                self::REQUEST_QUERY_MASS_ACTION_ALL_KEYS_SELECTED,
                self::REQUEST_QUERY_MASS_ACTION,
                self::REQUEST_QUERY_EXPORT,
                self::REQUEST_QUERY_PAGE,
                self::REQUEST_QUERY_LIMIT,
                self::REQUEST_QUERY_ORDER,
                self::REQUEST_QUERY_TEMPLATE,
                self::REQUEST_QUERY_RESET,
               
            );
            foreach ($requestQueries as $request_query) {
                unset($session[$request_query]);
            }
```
By adding MassActionColumn::ID (__action) to this array, the problem does not occur.
Is it the right way to solve this issue ? Can you explain me this code ?

Thank you !

**Comment by Abhoryo** [comment]
Filters is stor by column id in the session, so to get every filters, we have to remove others data.
Yeah you can add massaction id to this column.

**Comment by DonCallisto** [comment]
Hello @Abhoryo @plfort 

I've seen that this will fix `getFilter($columnId)` called in any closure passed not only to `manipulateQuery` but also to `manipulateRow`

One issue that's killing me:

    foreach ($session as $columnId => $sessionFilter) {
        if (isset($sessionFilter['operator'])) {
            $operator = $sessionFilter['operator'];
            unset($sessionFilter['operator']);
        } else {
            $operator = $this->getColumn($columnId)->getDefaultOperator();
        }

        if (!isset($sessionFilter['to'])) {
            $sessionFilter = $sessionFilter['from'];
        }

        $this->sessionFilters[$columnId] = new Filter($operator, $sessionFilter);
    }

It seems that `$sessionFilter`, after mass action redirect, keeps *ALL* filters setted onto grid. This lead to a `$sessionFilter['from']` error if there's even one filter without any value setted into grid.

What I've done to mitigate that issue is wrap

    if (!isset($sessionFilter['to'])) {
        $sessionFilter = $sessionFilter['from'];
    }

    $this->sessionFilters[$columnId] = new Filter($operator, $sessionFilter);

into

    if (isset($sessionFilter['from']) {
        if (!isset($sessionFilter['to'])) {
            $sessionFilter = $sessionFilter['from'];
        }

        $this->sessionFilters[$columnId] = new Filter($operator, $sessionFilter);
    }

Is this the right way? Shouldn't maybe filters be posted if hasn't any value? Is there anybody who can confirm this or point me in the right direction? Thank you.
