### ISSUE TITLE
Revise Tests

### ISSUE THREAD

**Issue by hmert** [APY/APYDataGridBundle#787]
- [ ] BC for Symfony `< 2.8`

**Comment by qferr** [comment]
:+1:

**Comment by hmert** [comment]
@qferr will you revise the tests?

**Comment by qferr** [comment]
@hmert Why not. We must check the code quality to avoid breaking backward compatibility like the PR-782.

**Comment by DonCallisto** [comment]
Is this issue somehow related to this PR --> https://github.com/APY/APYDataGridBundle/pull/909 ?
If so, please report all things into PR and close this, we should do a little clean of issues as 52 is a pretty huge number. We should have an actual idea of what really should be fixed and what is already done and so on.

Moreover I would like to have from you an update of your commitment as members and maintainer as I've noticed that the activity on this bundle, apart mine recent collaboration, is dropped down dramatically again. This is an important information for the community, IMHO.

**Comment by hmert** [comment]
@DonCallisto closed

**Comment by DonCallisto** [comment]
Ok, could you (and others of course) gently answer my question?
Thanks.

**Comment by hmert** [comment]
@DonCallisto 

Firstly, I want to express my deep appreciation for the help and support you have offered us on this project. I feel so grateful to you for taking time out of your life to answer so many questions or development. Without your help, We would not have been able to complete `v3` and `tests`.

We have been working on @OJS which is very complicated project both software design and academic needs. Unfortunately, we haven't focused that much last Q2-3 of 2016. APY is a big dependency of OJS's, and so we do need to maintain just only `2.x` at these months for 2016.

Fact 1: **Current APY@2.x is mostly stable and meet expectations.** 

Fact 2: Lot's of questions are not related to bugs or feature requests, answering and resolving takes much time we think. Like you/us and most of fresh contributor/member has spent time to answer or resolve this type of issues. After some time, We realized that we have to go forward instead of spending time not to break BC.

But PHP community needs yet another or alternative grid.

Our plan is make a `v3` at 2017 Q1-2.

I hope all maintainers/members will be with us.

Best wishes to all.

**Comment by DonCallisto** [comment]
@hmert thank you for your answer and your mentions here.

I will not be long but I strongly believe that maintainers and members should put some time to answer even smalls issues (I don't have full understanding of bundle, otherwise I would help to) because, otherwise from community POV, this bundle seems to be "on hold" again like it was after @Abhoryo left the project, and this is not a good impression.

I would be happy if also other members had replied to my question but no problem, I perfectly understand your post.

Let's hope that `v3` is going to raise some enthusiasm again :)

P.S.: If you need help with OJS let me know as, as soon as I finish with this bundle test, I have nothing to do speaking of open source.
