### ISSUE TITLE
Rollback #806

### ISSUE THREAD

**Issue by plfort** [APY/APYDataGridBundle#807]
Last merge change the grid behaviour, the grid does not apply filter is you don't specify the default fitler !
Please test before merging

**Comment by b-durand** [comment]
We should have unit tests for testing regression.

**Comment by delirehberi** [comment]
@plfort sorry for that #807

**Comment by MlleDelphine** [comment]
I propose the change. I encountered no issue.

Could you precise yours ?

It's not correct to let people chosing "contains" if it throw an exception that's why I propose this and I've tested it.

**Comment by plfort** [comment]
I don't know how you get your error, DateColumn extends DateTimeColumn and this one defines defaultOperator as  OPERATOR_EQ on line 46.
Do you have a custom DateColumn that extends directly Column ?

**Comment by MlleDelphine** [comment]
"Contains" is operator "LIKE" (self::OPERATOR_LIKE) not "eq".

In my entity I have defined `operators={"eq", "neq", "gt", "lt", "gte", "lte", "btw", "btwe"}, type="datetime",` and because "like" is not in the list and default operator for abstract class Column it throws an error 
![like operator not found in operators list 500 internal server error - mozilla firefox](https://cloud.githubusercontent.com/assets/11458134/12143119/358b0002-b47e-11e5-9da5-6c63120250ba.jpg)

**Comment by b-durand** [comment]
@MlleDelphine try this ```operators={"eq", "neq", "gt", "lt", "gte", "lte", "btw", "btwe"}, defaultOperator="eq", type="datetime",```

**Comment by plfort** [comment]
+1 @b-durand

**Comment by MlleDelphine** [comment]
Ok ! You are fabulous ! Thanks ! I did not know this property !
